### ISSUE TITLE
commits on other forks we may want to merge in

### ISSUE THREAD

**Issue by damianham** [ambercommunity/mongo.cr#2]
https://github.com/marzhaev/mongo.cr/commit/a4d305c04a35ce870bfa50ab30adf5882d7ab8c9
https://github.com/kimvex/mongo.cr/commit/3ffa9151c84ecac4682b6ce18eaba375fe9c9eb9
https://github.com/kimvex/mongo.cr/commit/80e8c13928ab1dcf95d0cc2bdbc13e71a700ae68
https://github.com/ikarigeorge/mongo.cr/commit/a5640d8170e4543c30e61abaa600a656c37d830a

**Comment by mixflame** [comment]
Those all look solid to me!
