### ISSUE TITLE
projection in collection.find() query

### ISSUE THREAD

**Issue by mpangrazzi** [ambercommunity/mongo.cr#5]
Hi,

is there a way to get only some fields in a `find()` query? 
In MongoDB console you normally do:

```
db.test.find({}, { name: 1 })
```

which matches all documents but returns only the `name` field.
Thank you!

**Comment by mpangrazzi** [comment]
Found it! :)

```
collection.find({} of String => String, { "name" => 1 }) do |doc|
  puts doc
end
```

Would be great to add an `example` folder with some examples or some docs.

**Comment by vectorselector** [comment]
yes, some examples or docs would be most useful.
How to drill into a BSON document... once I learn how to do it I'll happily provide some examples.
The readme.md is rather cursory (hehehe) in it's coverage of the functionality contained...
